openapi: 3.0.0
info:
  title: Generated API
  version: 1.0.0
components:
  schemas:
    artist:
      type: object
      properties:
        artist_id:
          type: integer
          x-af-primary-key: auto
          description: Unique identifier for the artist.
          example: 1
        name:
          type: string
          maxLength: 120
        album_items:
          type: array
          items:
            $ref: '#/components/schemas/album'
            x-af-child-property: artist_id
          description: List of album items associated with this artist.
      required:
      - artist_id
      x-af-database: chinook
    album:
      type: object
      properties:
        album_id:
          type: integer
          x-af-primary-key: auto
          description: Unique identifier for the album.
          example: 1
        title:
          type: string
          maxLength: 160
        artist_id:
          type: integer
        artist:
          $ref: '#/components/schemas/artist'
          x-af-parent-property: artist_id
          description: Artist associated with the album.
        track_items:
          type: array
          items:
            $ref: '#/components/schemas/track'
            x-af-child-property: album_id
          description: List of track items associated with this album.
      required:
      - album_id
      - title
      - artist_id
      x-af-database: chinook
    employee:
      type: object
      properties:
        employee_id:
          type: integer
          x-af-primary-key: auto
          description: Unique identifier for the employee.
          example: 1
        employee:
          $ref: '#/components/schemas/employee'
          x-af-parent-property: employee_id
          description: Employee associated with the employee.
        last_name:
          type: string
          maxLength: 20
        first_name:
          type: string
          maxLength: 20
        title:
          type: string
          maxLength: 30
        reports_to:
          type: integer
        birth_date:
          type: string
          format: date-time
        hire_date:
          type: string
          format: date-time
        address:
          type: string
          maxLength: 70
        city:
          type: string
          maxLength: 40
        state:
          type: string
          maxLength: 40
        country:
          type: string
          maxLength: 40
        postal_code:
          type: string
          maxLength: 10
        phone:
          type: string
          maxLength: 24
        fax:
          type: string
          maxLength: 24
        email:
          type: string
          maxLength: 60
        employee_items:
          type: array
          items:
            $ref: '#/components/schemas/employee'
            x-af-child-property: employee_id
          description: List of employee items associated with this employee.
      required:
      - employee_id
      - last_name
      - first_name
      x-af-database: chinook
    invoice:
      type: object
      properties:
        invoice_id:
          type: integer
          x-af-primary-key: auto
          description: Unique identifier for the invoice.
          example: 1
        customer_id:
          type: integer
        customer:
          $ref: '#/components/schemas/customer'
          x-af-parent-property: customer_id
          description: Customer associated with the invoice.
        invoice_date:
          type: string
          format: date-time
        billing_address:
          type: string
          maxLength: 70
        billing_city:
          type: string
          maxLength: 40
        billing_state:
          type: string
          maxLength: 40
        billing_country:
          type: string
          maxLength: 40
        billing_postal_code:
          type: string
          maxLength: 10
        total:
          type: number
        last_updated:
          type: string
          format: date-time
        invoice_line_items:
          type: array
          items:
            $ref: '#/components/schemas/invoice_line'
            x-af-child-property: invoice_id
          description: List of invoice_line items associated with this invoice.
      required:
      - invoice_id
      - customer_id
      - invoice_date
      - total
      - last_updated
      x-af-database: chinook
      x-af-concurrency-control: last_updated
    genre:
      type: object
      properties:
        genre_id:
          type: integer
          x-af-primary-key: auto
          description: Unique identifier for the genre.
          example: 1
        name:
          type: string
          maxLength: 120
        version:
          type: integer
        track_items:
          type: array
          items:
            $ref: '#/components/schemas/track'
            x-af-child-property: genre_id
          description: List of track items associated with this genre.
      required:
      - genre_id
      - version
      x-af-database: chinook
    invoice_line:
      type: object
      properties:
        invoice_line_id:
          type: integer
          x-af-primary-key: auto
          description: Unique identifier for the invoice_line.
          example: 1
        invoice_id:
          type: integer
        invoice:
          $ref: '#/components/schemas/invoice'
          x-af-parent-property: invoice_id
          description: Invoice associated with the invoice_line.
        track_id:
          type: integer
        track:
          $ref: '#/components/schemas/track'
          x-af-parent-property: track_id
          description: Track associated with the invoice_line.
        unit_price:
          type: number
        quantity:
          type: integer
      required:
      - invoice_line_id
      - invoice_id
      - track_id
      - unit_price
      - quantity
      x-af-database: chinook
    track:
      type: object
      properties:
        track_id:
          type: integer
          x-af-primary-key: auto
          description: Unique identifier for the track.
          example: 1
        name:
          type: string
          maxLength: 200
        album_id:
          type: integer
        album:
          $ref: '#/components/schemas/album'
          x-af-parent-property: album_id
          description: Album associated with the track.
        media_type_id:
          type: integer
        media_type:
          $ref: '#/components/schemas/media_type'
          x-af-parent-property: media_type_id
          description: Media_type associated with the track.
        genre_id:
          type: integer
        genre:
          $ref: '#/components/schemas/genre'
          x-af-parent-property: genre_id
          description: Genre associated with the track.
        composer:
          type: string
          maxLength: 220
        milliseconds:
          type: integer
        bytes:
          type: integer
        unit_price:
          type: number
        invoice_line_items:
          type: array
          items:
            $ref: '#/components/schemas/invoice_line'
            x-af-child-property: track_id
          description: List of invoice_line items associated with this track.
        playlist_track_items:
          type: array
          items:
            $ref: '#/components/schemas/playlist_track'
            x-af-child-property: track_id
          description: List of playlist_track items associated with this track.
      required:
      - track_id
      - name
      - media_type_id
      - milliseconds
      - unit_price
      x-af-database: chinook
    playlist:
      type: object
      properties:
        playlist_id:
          type: integer
          x-af-primary-key: auto
          description: Unique identifier for the playlist.
          example: 1
        name:
          type: string
          maxLength: 120
        playlist_track_items:
          type: array
          items:
            $ref: '#/components/schemas/playlist_track'
            x-af-child-property: playlist_id
          description: List of playlist_track items associated with this playlist.
      required:
      - playlist_id
      x-af-database: chinook
    playlist_track:
      type: object
      properties:
        playlist_id:
          type: integer
          x-af-primary-key: true
        playlist:
          $ref: '#/components/schemas/playlist'
          x-af-parent-property: playlist_id
          description: Playlist associated with the playlist_track.
        track_id:
          type: integer
          x-af-primary-key: true
        track:
          $ref: '#/components/schemas/track'
          x-af-parent-property: track_id
          description: Track associated with the playlist_track.
      required:
      - playlist_id
      - track_id
      x-af-database: chinook
    media_type:
      type: object
      properties:
        media_type_id:
          type: integer
          x-af-primary-key: auto
          description: Unique identifier for the media_type.
          example: 1
        name:
          type: string
          maxLength: 120
        track_items:
          type: array
          items:
            $ref: '#/components/schemas/track'
            x-af-child-property: media_type_id
          description: List of track items associated with this media_type.
      required:
      - media_type_id
      x-af-database: chinook
    customer:
      type: object
      properties:
        customer_id:
          type: integer
          x-af-primary-key: auto
          description: Unique identifier for the customer.
          example: 1
        first_name:
          type: string
          maxLength: 40
        last_name:
          type: string
          maxLength: 20
        company:
          type: string
          maxLength: 80
        address:
          type: string
          maxLength: 70
        city:
          type: string
          maxLength: 40
        state:
          type: string
          maxLength: 40
        country:
          type: string
          maxLength: 40
        postal_code:
          type: string
          maxLength: 10
        phone:
          type: string
          maxLength: 24
        fax:
          type: string
          maxLength: 24
        email:
          type: string
          maxLength: 60
        support_rep_id:
          type: integer
        version_stamp:
          type: string
          format: uuid
        invoice_items:
          type: array
          items:
            $ref: '#/components/schemas/invoice'
            x-af-child-property: customer_id
          description: List of invoice items associated with this customer.
      required:
      - customer_id
      - first_name
      - last_name
      - email
      - version_stamp
      x-af-database: chinook
